config/routes.rb
Rails.application.routes.draw do
  root "flights#index"
  resources :flights, only: [ :index ]
  resources :bookings, only: [ :new, :create, :show ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: "Flight", foreign_key: "departure_airport_id"
  has_many :arriving_flights, class_name: "Flight", foreign_key: "arrival_airport_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"
  has_many :bookings
  has_many :passengers, through: :bookings

  def self.find_flights(controller_params)
    if valid_controller_params?(controller_params)

      source = controller_params[:departure]
      target = controller_params[:destination]
      date, month, year = controller_params[:date_and_time].split.first.split("-")
      date_time = [ year, month, date ].join("-")

      source_airport = Airport.find_by(code: source)
      target_airport = Airport.find_by(code: target)
      flights = Flight.where(departure_airport: source_airport).where(arrival_airport: target_airport)
      flights.reject { |flight| flight.starts_at.to_s.split.first != date_time }
    end
  end

  def self.valid_controller_params?(controller_params)
    controller_params[:departure] && controller_params[:destination] && controller_params[:date_and_time]
  end

  private_class_method :valid_controller_params?
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
  has_many :flights, through: :booking

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find(params[:flight])
    @passenger_count = params[:passengers].to_i
    @booking = Booking.new
    @passenger_count.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      @booking.passengers.each { |passenger| PassengerMailer.with(booking_info: @booking, passenger: passenger).ticket_booked.deliver_now }
      redirect_to @booking, notice: "Booking was successful!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show = (@booking = Booking.find(params[:id]))

  private

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [ :name, :email ])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @locations = Airport.all.order(city: :asc).pluck(:city, :code)
    @passengers = [ *1..4 ]
    @dates = Flight.all.order(starts_at: :asc).map { |flight| flight.starts_at.strftime("%d-%m-%Y | %I:%M %p") }.uniq
    @available_flights = nil || Flight.find_flights(flight_params)
    @passenger_count = params[:passengers]
  end

  private

  def flight_params = params.permit(:departure, :destination, :date_and_time, :passengers)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/_flight.html.erb
<div class="flight-details">
  <p>
    <strong>Flight no &nbsp;&nbsp;:
    </strong><%= flight.id %>
  </p>
  <p>
    <strong>Departs from:
    </strong><%= flight.departure_airport.city %>(<%= flight.departure_airport.code %>)
  </p>
  <p>
    <strong>Arrives to &nbsp;:
    </strong><%= flight.arrival_airport.city %>(<%= flight.arrival_airport.code %>)
  </p>
  <p>
    <strong>Leaves at &nbsp;&nbsp;:
    </strong><%= flight.starts_at.strftime("%d-%b-%Y | %I:%M %p") %>
  </p>
</div>

app/views/bookings/_form.html.erb
<%= form_with model: booking do |booking_form| %>
  <div class="passenger-form-container">
    <%= booking_form.fields_for :passengers do |passenger_form| %>
      <div class="passenger-fields">
        <div>
          <div><%= passenger_form.label :name %></div>
          <div><%= passenger_form.text_field :name, placeholder: "John Doe", required: true %></div>
        </div>
        <div>
          <div><%= passenger_form.label :email %></div>
          <div><%= passenger_form.email_field :email,
                                       placeholder: "johndoe@example.com",
                                       required: true %></div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="modify-passenger" data-controller="passenger" data-passenger-count-value= <%= passenger_count %>>
    <button data-action="passenger#add">Add Passenger</button>
    <button data-action="passenger#remove">Remove Passenger</button>
  </div>
  <div>
    <%= booking_form.hidden_field "flight_id", value: flight_id %>
    <%= booking_form.submit "Confirm Ticket" %>
  </div>
<% end %>

app/views/bookings/new.html.erb
<div class="passenger">
  <div class="flight-details-wrapper">
    <h2>Flight details</h2>
    <%= render partial: "flight", locals: { flight: @flight } %>
  </div>
  <div class="passenger-form">
    <h2>Fill out the Passenger details</h2>
    <%= render partial: "form",
    locals: {
      booking: @booking,
      flight_id: @flight.id,
      passenger_count: @passenger_count,
    } %>
  </div>
</div>

<template>
  <div class="passenger-fields">
    <div>
      <div><%= label_tag :name %></div>
      <div><%= text_field_tag :name, nil, placeholder: "John Doe", required: true %></div>
    </div>
    <div>
      <div><%= label_tag :email %></div>
      <div><%= email_field_tag :email, nil, placeholder: "johndoe@example.com", required: true %></div>
    </div>
  </div>
</template>

app/views/bookings/show.html.erb
<div class="ticket-details-wrapper">
  <div class="ticket-details">
    <h2>Your booking was succesful! Bon Voyage!!</h2>
    <% @booking.passengers.each do |passenger| %>
      <div>
        <h3><%= passenger.name %></h3>
        <%= render partial: "flight", locals: { flight: @booking.flight } %>
      </div>
    <% end %>
  </div>
</div>

app/views/flights/_flight_picker.html.erb
<%= form_with method: :get, url: flights_path do |form| %>
  <div>
    <div>
      <%= form.label :departure %>
    </div>
    <div>
      <%= form.select :departure,
                  locations,
                  { prompt: "Select your departure location" },
                  required: true %>
    </div>
  </div>
  <div>
    <div>
      <%= form.label :destination %>
    </div>
    <div>
      <%= form.select :destination,
                  locations,
                  { prompt: "Select your destination location" },
                  required: true %>
    </div>
  </div>
  <div>
    <div>
      <%= form.label :passengers %>
    </div>
    <div>
      <%= form.select :passengers,
                  passengers,
                  { prompt: "Select passengers count" },
                  required: true %>
    </div>
  </div>
  <div>
    <div>
      <%= form.label :date_and_time %>
    </div>
    <div>
      <%= form.select :date_and_time,
                  dates,
                  { prompt: "Select your date and time" },
                  required: true %>
    </div>
  </div>
  <div>
    <%= form.submit "Available Flights" %>
  </div>
<% end %>

app/views/flights/_search_flights.html.erb
<div class="available-flights">
  <% if available_flights %>
    <%= form_with method: :get, url: new_booking_path do |form| %>
      <% available_flights.each do |flight| %>
        <div>
          <%= form.hidden_field "passengers", value: passenger_count %>
          <div>
            <%= form.radio_button :flight, flight.id, options = { id: "flight", required: true } %>
            <%= form.label :flight,
                       "#{flight.id} : #{flight.departure_airport.city}(#{flight.departure_airport.code}) -> #{flight.arrival_airport.city}(#{flight.arrival_airport.code}) departs on #{flight.starts_at.to_formatted_s} " %>
          </div>
          <div>
            <%= form.submit "Book Flight" %>
          </div>
        </div>
      <% end %>
      <% if !available_flights.nil? && available_flights.empty? %>
        <h2 class="no-flights">No flights found!</h2>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/flights/index.html.erb
<div class="flight-picker">
  <%= render partial: "flight_picker",
  locals: {
    locations: @locations,
    passengers: @passengers,
    dates: @dates,
  } %>
  <%= render partial: "search_flights",
  locals: {
    available_flights: @available_flights,
    passenger_count: @passenger_count,
  } %>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <h1><%= link_to "Flight Booker", root_path %></h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Odin Flight Booker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render partial: "layouts/header" %>
    <%= yield %>
  </body>
</html>